// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://famcotleecuylwaxiekk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhbWNvdGxlZWN1eWx3YXhpZWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NjI5OTgsImV4cCI6MjA1ODEzODk5OH0.F7P_1HQbdDQijjj-PQU3E2iMARlxz6vzuu68NSoa8XE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);